version: "3.0"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=123
      - PGDATA=/var/lib/postgresql/pgdata/
      - POSTGRES_DB=pizzadb
    volumes:
      - pgdata:/var/lib/postgresql/pgdata/
    ports:
      - 5432:5432
  web:
    tty: true
    build: .
    volumes:
      - .:/src/
    depends_on:
      - db
    command: "python ./manage.py runserver 0.0.0.0:8000"

  nginx:
    image: nginx:1.23.2-alpine
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./static:/static:ro
      - media:/media:ro
    links:
      - web
    depends_on:
      - web
    ports:
      - "8000:80"
volumes:
  pgdata: { }
  static: { }
  media: { }
