# Generated by Django 4.2 on 2023-04-18 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='description',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='category',
        ),
        migrations.AddField(
            model_name='pizza',
            name='is_custom',
            field=models.BooleanField(default=False, verbose_name='Is it custom'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
