# Generated by Django 4.2 on 2023-04-18 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0002_remove_ingredient_description_remove_pizza_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='price',
            field=models.FloatField(blank=True, verbose_name='Price'),
        ),
    ]
