# Generated by Django 4.2 on 2023-04-18 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0003_alter_pizza_description_alter_pizza_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='price',
            field=models.FloatField(blank=True, default=50.0, verbose_name='Price'),
        ),
    ]
