# Generated by Django 4.2 on 2023-04-21 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0005_order_comments_order_name_order_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
    ]
